name: "languages-env-base-plugin"
description: "Languages environment base plugin"
types: 
  - env
tags:
  - environment
  - kotlin
  - container
inputs:
  - label: "Application name:"
    type: text
    name: "project_name"
  - label: "Application group id:"
    type: text
    name: "project_group_id"
    condition:
      variable: "language"
      operator: "=="
      value: "kotlin"
  - label: "Application version:"
    type: text
    name: "project_version"
computedInputs:
  "app_class_name": "{{inputs.project_name|title|replace(' ', '')}}"
